services:
  - type: web
    name: tezsavdo
    env: python
    pythonVersion: 3.12.18
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
