from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('mahsulotlar/', views.mahsulotlar, name='mahsulotlar'),
    path('mahsulot/<slug:slug>/', views.mahsulot_detali, name='product_detail'),
    path('api/mahsulot/<int:mahsulot_id>/variant/', views.variant_info, name='variant_info'),
    path('savatcha/', views.savatcha, name='savatcha'),
    path('api/savatcha/soni/', views.savatcha_soni_api, name='savatcha_soni_api'),
    path('api/savatcha/qoshish/', views.savatcha_qoshish, name='savatcha_qoshish'),
    path('savatcha/<int:item_id>/miqdor/', views.savatcha_miqdor, name='savatcha_miqdor'),
    path('savatcha/<int:item_id>/olib-tashlash/', views.savatcha_olib_tashlash, name='savatcha_olib_tashlash'),
    path('savatcha/tozalash/', views.savatcha_tozalash, name='savatcha_tozalash'),
    path('checkout/', views.checkout, name='checkout'),
    path('buyurtma/<int:id>/', views.buyurtma_detali, name='buyurtma_detali'),
    path('chek/<int:id>/', views.chek, name='chek'),
    path('qr-kod/<int:id>/', views.qr_kod, name='qr_kod'),
    path('panel/qr-skaner/', views.admin_qr_skaner, name='admin_qr_skaner'),
    path('panel/qr-tasdiqlash/', views.admin_qr_tasdiqlash, name='admin_qr_tasdiqlash'),
    path('mening-buyurtmalarim/', views.mening_buyurtmalarim, name='mening_buyurtmalarim'),
    path('kirish/', views.kirish, name='kirish'),
    path('royxatdan-otish/', views.royxatdan_otish, name='royxatdan_otish'),
    path('chiqish/', views.chiqish, name='chiqish'),
    path('profil/', views.profil, name='profil'),
    path('parol-ozgartirish/', views.parol_ozgartirish, name='parol_ozgartirish'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('manzillarni-boshqarish/', views.manzillar, name='manzillar'),
    path('istaknafarim/', views.istaknafarim, name='istaknafarim'),
    path('istaknafarim/<int:mahsulot_id>/qoshish/', views.istakga_qoshish, name='istakga_qoshish'),
    path('istaknafarim/<int:mahsulot_id>/olib-tashlash/', views.istakdan_olib_tashlash, name='istakdan_olib_tashlash'),
    path('sozlamalar/', views.sozlamalar, name='sozlamalar'),
    path('parol-tiklash/', views.parol_tiklash, name='parol_tiklash'),
    path('buyurtmani-kuzatish/', views.buyurtmani_kuzatish, name='buyurtmani_kuzatish'),
    path('kuponlar/', views.kuponlar, name='kuponlar'),
    path('bonuslar/', views.bonuslar, name='bonuslar'),
    path('bildirishnomalar/', views.bildirishnomalar, name='bildirishnomalar'),
    path('biz-haqimizda/', views.biz_haqimizda, name='biz_haqimizda'),
    path('faq/', views.faq, name='faq'),
    path('blog/', views.blog, name='blog'),
    path('aloqa/', views.aloqa, name='aloqa'),
    path('brendlar/', views.brendlar, name='brendlar'),
    path('aksiyalar/', views.aksiyalar, name='aksiyalar'),
    path('yangi-mahsulotlar/', views.yangi_mahsulotlar, name='yangi_mahsulotlar'),
    path('ko-p-sotilganlar/', views.ko_p_sotilganlar, name='ko_p_sotilganlar'),
    path('taqqoslash/', views.taqqoslash, name='taqqoslash'),
    path('oxirgi-korilgan/', views.oxirgi_korilgan, name='oxirgi_korilgan'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
