# Generated by Django 5.0.1 on 2026-08-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoKarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Masalan: Demo karta 1', max_length=100)),
                ('tur', models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo'), ('visa', 'Visa'), ('mastercard', 'MasterCard')], max_length=20)),
                ('karta_raqami', models.CharField(help_text='Masalan: 8600 1234 5678 9012', max_length=20, unique=True)),
                ('amal_qilish_muddati', models.CharField(help_text='MM/YY', max_length=7)),
                ('balans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holat', models.CharField(choices=[('faol', 'Faol'), ('nofaol', 'Nofaol')], default='faol', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo karta',
                'verbose_name_plural': 'Demo kartalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='kutilmoqda', max_length=20)),
                ('izoh', models.TextField(blank=True, help_text='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheklari', to='shop.buyurtma')),
                ('demo_karta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheklari', to='shop.demokarta')),
            ],
            options={
                'verbose_name': 'Chek',
                'verbose_name_plural': 'Cheklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tolom',
            name='demo_karta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolovlar', to='shop.demokarta'),
        ),
    ]
