# Generated by Django 5.0.1 on 2026-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_demokarta_chek_tolom_demo_karta'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='qr_kod',
            field=models.ImageField(blank=True, null=True, upload_to='qr_kodlar/'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='qr_kod_yaratildi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('jonatilgan', 'Yuborilgan'), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi'), ('qr_kutilmoqda', 'QR kod kutilmoqda'), ('qr_tasdiqlandi', 'QR tasdiqlandi')], default='kutilmoqda', max_length=20),
        ),
    ]
