# Generated by Django 5.0.1 on 2026-08-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_buyurtma_qr_kod_buyurtma_qr_kod_yaratildi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaytMalumotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('qiymat', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Sayt ma'lumoti",
                'verbose_name_plural': "Sayt ma'lumotlari",
            },
        ),
    ]
