# Generated by Django 5.0.1 on 2026-08-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_saytmalumotlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='baholandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('yigilmoqda', "Yig'ilmoqda"), ('jonatilgan', 'Yuborilgan'), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi'), ('qr_kutilmoqda', 'QR kod kutilmoqda'), ('qr_tasdiqlandi', 'QR tasdiqlandi')], default='kutilmoqda', max_length=20),
        ),
    ]
