# Generated by Django 5.0.1 on 2026-08-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_buyurtma_baholandi_alter_buyurtma_holat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('kalit', models.CharField(max_length=50, unique=True)),
                ('turi', models.CharField(choices=[('color', 'Rang'), ('text', 'Matn'), ('number', 'Raqam'), ('boolean', 'Mantiqiy')], default='text', max_length=20)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variant turi',
                'verbose_name_plural': 'Variant turlari',
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('qiymat', models.CharField(max_length=100)),
                ('rang_kod', models.CharField(blank=True, help_text='Rang uchun HEX kod', max_length=10)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Variant qiymati',
                'verbose_name_plural': 'Variant qiymatlari',
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Variant opsiyasi',
                'verbose_name_plural': 'Variant opsiyalari',
                'ordering': ['option_value__option_type__tartib', 'option_value__tartib'],
            },
        ),
        migrations.CreateModel(
            name='VariantRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='variantlar/rasmlar/')),
                ('asosiy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variant rasmi',
                'verbose_name_plural': 'Variant rasmlari',
                'ordering': ['-asosiy', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='mahsulotvariant',
            options={'ordering': ['id'], 'verbose_name': 'Mahsulot varianti', 'verbose_name_plural': 'Mahsulot variantlari'},
        ),
        migrations.RemoveField(
            model_name='mahsulotvariant',
            name='hajm',
        ),
        migrations.RemoveField(
            model_name='mahsulotvariant',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='mahsulotvariant',
            name='rang_kod',
        ),
        migrations.AddField(
            model_name='mahsulotvariant',
            name='eski_narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mahsulotvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variantlar/'),
        ),
        migrations.AddField(
            model_name='mahsulotvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahsulotvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='mahsulotvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='jami',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='buyurtmamahsulot',
            name='jami',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='buyurtmamahsulot',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='eski_narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mahsulotvariant',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tolom',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['slug'], name='shop_mahsul_slug_27b949_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['is_active', '-created_at'], name='shop_mahsul_is_acti_4f7bce_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['kategoriya', 'is_active'], name='shop_mahsul_kategor_584091_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['brend', 'is_active'], name='shop_mahsul_brend_i_b96234_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['-sotish_soni'], name='shop_mahsul_sotish__79087b_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['-reyting'], name='shop_mahsul_reyting_a456de_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulotvariant',
            index=models.Index(fields=['mahsulot', 'is_active'], name='shop_mahsul_mahsulo_c4d053_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulotvariant',
            index=models.Index(fields=['sku'], name='shop_mahsul_sku_0ba2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulotvariant',
            index=models.Index(fields=['soni'], name='shop_mahsul_soni_d520da_idx'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qiymatlar', to='shop.optiontype'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_ops', to='shop.optionvalue'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_ops', to='shop.mahsulotvariant'),
        ),
        migrations.AddField(
            model_name='variantrasm',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='shop.mahsulotvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together={('option_type', 'qiymat')},
        ),
        migrations.AlterUniqueTogether(
            name='variantoption',
            unique_together={('variant', 'option_value')},
        ),
    ]
