# Generated by Django 5.0.1 on 2026-08-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_optiontype_optionvalue_variantoption_variantrasm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulotvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
